<?php $presets["skin14r"] = array (
  'advanced-normalize_resize_on_mobile' => '1',
  'advanced-speed_img_resize' => '1',
  'blog-fancy_date-style' => 'vertical',
  'blog-thumbnail_proportions' => 
  array (
    'width' => 2,
    'height' => 1,
  ),
  'blog-thumbnail_size' => 'resize',
  'bottom_bar-bg_color' => 'rgba(255,255,255,0.12)',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-collapse_after' => '990px',
  'bottom_bar-color' => '#85868c',
  'bottom_bar-credits' => '1',
  'bottom_bar-enabled' => '1',
  'bottom_bar-height' => '60px',
  'bottom_bar-layout' => 'logo_left',
  'bottom_bar-logo-padding' => '10px 15px 10px 0px',
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin14r.bottom-bar-logo-hd.png?w=56&h=56',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin14r.bottom-bar-logo-regular.png?w=28&h=28',
    1 => 0,
  ),
  'bottom_bar-menu-collapse_after' => '778px',
  'bottom_bar-padding' => '10px 10px',
  'bottom_bar-style' => 'full_width_line',
  'breadcrumbs-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => 12,
    'line_height' => 22,
    'text_transform' => 'uppercase',
  ),
  'breadcrumbs_bg_color' => 'rgba(255,255,255,0.2)',
  'breadcrumbs_border_color' => 'rgba(130,36,227,0.2)',
  'breadcrumbs_border_radius' => '2px',
  'breadcrumbs_border_width' => '0px',
  'breadcrumbs_margin' => '0px 0px 0px 0px',
  'breadcrumbs_padding' => '0px 0px 0px 0px',
  'buttons-border-color' => '#ffffff',
  'buttons-border-color_mode' => 'accent',
  'buttons-color' => '#4f4f4f',
  'buttons-color_gradient' => '135deg|#dd3333 30%|#3a892a 100%',
  'buttons-color_mode' => 'accent',
  'buttons-hover-border-color' => '#ffffff',
  'buttons-hover-border-color_mode' => 'accent',
  'buttons-hover_color' => '#cba36f',
  'buttons-hover_color_gradient' => '135deg|#cc4789 30%|#e57544 100%',
  'buttons-hover_color_mode' => 'color',
  'buttons-l-icon-size' => 18,
  'buttons-l-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => 18,
    'text_transform' => 'none',
  ),
  'buttons-l_border_radius' => '0px',
  'buttons-l_border_width' => '0px',
  'buttons-l_padding' => '16px 24px 16px 24px',
  'buttons-m-icon-size' => 14,
  'buttons-m-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => 14,
    'text_transform' => 'none',
  ),
  'buttons-m_border_radius' => '0px',
  'buttons-m_border_width' => '0px',
  'buttons-m_padding' => '10px 18px 10px 18px',
  'buttons-s-icon-size' => 12,
  'buttons-s-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => 12,
    'text_transform' => 'none',
  ),
  'buttons-s_border_radius' => '0px',
  'buttons-s_border_width' => '0px',
  'buttons-s_padding' => '7px 14px 7px 14px',
  'buttons-style' => 'flat',
  'buttons-text_color' => '#ffffff',
  'buttons-text_color_mode' => 'color',
  'buttons-text_hover_color' => '#ffffff',
  'buttons-text_hover_color_mode' => 'color',
  'contact_form_message' => '1',
  'content-headers_color' => '#333333',
  'content-links_color' => '#d8b280',
  'content-primary_text_color' => '#85868c',
  'content-secondary_text_color' => '#b4b5bb',
  'custom_error_messages' => 'The message has not been sent. Please try again.',
  'custom_error_messages_validation' => 'One or more fields have an error. Please check and try again.',
  'custom_success_messages' => 'Your message has been sent.',
  'dividers-color' => 'rgba(0,0,0,0.08)',
  'filter-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => 14,
    'text_transform' => 'uppercase',
  ),
  'fonts-big_size' => 16,
  'fonts-big_size_line_height' => 28,
  'fonts-font_family' => 'Roboto',
  'fonts-h1-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => '44',
    'line_height' => '54',
    'text_transform' => 'none',
  ),
  'fonts-h2-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => '34',
    'line_height' => '44',
    'text_transform' => 'none',
  ),
  'fonts-h3-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => '24',
    'line_height' => '34',
    'text_transform' => 'none',
  ),
  'fonts-h4-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => '20',
    'line_height' => '30',
    'text_transform' => 'none',
  ),
  'fonts-h5-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => '16',
    'line_height' => '26',
    'text_transform' => 'none',
  ),
  'fonts-h6-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => '14',
    'line_height' => '24',
    'text_transform' => 'none',
  ),
  'fonts-normal_size' => 15,
  'fonts-normal_size_line_height' => 27,
  'fonts-small_size' => 13,
  'fonts-small_size_line_height' => 23,
  'footer-accent_text_color' => '',
  'footer-bg_color' => 'rgba(26,28,32,1)',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-collapse_after' => '778px',
  'footer-collapse_columns_after' => '778px',
  'footer-decoration' => 'none',
  'footer-decoration_outline_color' => 'rgba(129,215,66,0.96)',
  'footer-headers_color' => '#ffffff',
  'footer-is_fullwidth' => '0',
  'footer-mobile_padding' => '50px 20px 10px 20px',
  'footer-padding' => '50px 50px 10px 50px',
  'footer-paddings-columns' => '25px',
  'footer-primary_text_color' => '#85868c',
  'footer-slide-out-mode' => '0',
  'footer-style' => 'solid_background',
  'general-accent_bg_color' => '#d8b280',
  'general-accent_bg_color_gradient' => '135deg|#2578e9 30%|#3fe7d9 100%',
  'general-accent_color_mode' => 'color',
  'general-album_back_button_url' => '',
  'general-album_meta_author' => false,
  'general-album_meta_categories' => '1',
  'general-album_meta_comments' => false,
  'general-album_meta_date' => '1',
  'general-album_meta_on' => '1',
  'general-bg_color' => 'rgba(255,255,255,1)',
  'general-bg_fixed' => false,
  'general-bg_fullscreen' => false,
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-border_radius' => '0px',
  'general-box_width' => '1340px',
  'general-boxed_bg_color' => '#ffffff',
  'general-boxed_bg_fixed' => '1',
  'general-boxed_bg_fullscreen' => false,
  'general-boxed_bg_image' => 
  array (
    'image' => '/images/backgrounds/patterns/full/grey_wood.jpg',
    'repeat' => 'repeat',
    'position_x' => 'left',
    'position_y' => 'top',
  ),
  'general-breadcrumbs_bg_color' => 'disabled',
  'general-breadcrumbs_color' => '#ffffff',
  'general-content_boxes_bg_color' => '#f5f5f5',
  'general-content_boxes_decoration' => 'none',
  'general-content_boxes_decoration_outline_color' => 'rgba(0,0,0,0)',
  'general-content_width' => '1300px',
  'general-custom_css' => '',
  'general-custom_loader' => '',
  'general-filter-margin' => '0px 2px 0px 2px',
  'general-filter-padding' => '7px 12px 7px 12px',
  'general-filter_style' => 'minimal',
  'general-filter_style-material-line_size' => '2px',
  'general-filter_style-minimal-border_radius' => '0px',
  'general-fullscreen_overlay_color' => 'rgba(255,255,255,1)',
  'general-fullscreen_overlay_color_mode' => 'color',
  'general-fullscreen_overlay_gradient' => '135deg|#8224e3 30%|#dd3333 100%',
  'general-fullscreen_overlay_opacity' => 100,
  'general-images_lazy_loading' => '1',
  'general-layout' => 'wide',
  'general-lightbox_arrow_size' => '62px',
  'general-lightbox_overlay_opacity' => 85,
  'general-loader_style' => 'double_circles',
  'general-navigation_margin' => '50px',
  'general-next_prev_in_album' => '1',
  'general-page-title-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => 20,
    'line_height' => 30,
    'text_transform' => 'uppercase',
  ),
  'general-page_content_margin' => '70px 50px 70px 50px',
  'general-page_content_mobile_margin' => '70px 20px 70px 20px',
  'general-portfolio_thumbnail_proportions' => 
  array (
    'width' => 2,
    'height' => 1,
  ),
  'general-portfolio_thumbnail_size' => 'resize',
  'general-post_back_button_url' => '',
  'general-project_back_button_url' => '',
  'general-rel_posts_head_title' => 'Related posts',
  'general-rel_posts_max' => 6,
  'general-responsive' => '1',
  'general-responsive_title_height' => '0px',
  'general-responsive_title_line_height' => 30,
  'general-responsive_title_size' => 20,
  'general-show_back_button_in_album' => '1',
  'general-show_breadcrumbs' => '1',
  'general-show_rel_posts' => '1',
  'general-show_titles' => '1',
  'general-smooth_scroll' => 'off',
  'general-spinner_color' => 'rgba(216,178,128,1)',
  'general-switch_content_paddings' => '778px',
  'general-title_align' => 'left',
  'general-title_bg_color' => 'rgba(216,178,128,1)',
  'general-title_bg_fullscreen' => false,
  'general-title_bg_gradient' => '0deg|#4a66d6 30%|#12b4ea 100%',
  'general-title_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'no-repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'general-title_bg_mode' => 'background',
  'general-title_bg_overlay' => false,
  'general-title_bg_parallax' => '',
  'general-title_color' => '#ffffff',
  'general-title_decoration' => 'none',
  'general-title_decoration_line_color' => 'rgba(51,51,51,0.11)',
  'general-title_decoration_line_height' => '5px',
  'general-title_decoration_line_style' => 'dashed',
  'general-title_decoration_outline_color' => 'rgba(30,115,190,0)',
  'general-title_decoration_outline_height' => '1px',
  'general-title_decoration_outline_style' => 'solid',
  'general-title_enable_bg_img' => 'disabled',
  'general-title_height' => '0px',
  'general-title_overlay_color' => 'rgba(0,0,0,0.5)',
  'general-title_responsive_breadcrumbs' => false,
  'general-title_scroll_effect' => 'default',
  'general-titles-responsiveness-switch' => '778px',
  'general-titles_responsiveness' => '1',
  'header-background' => 'normal',
  'header-bg-color' => 'rgba(255,255,255,1)',
  'header-bg-image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg-is_fixed' => false,
  'header-bg-is_fullscreen' => false,
  'header-classic-elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'custom_menu',
      1 => 'cart',
    ),
    'top_bar_right' => 
    array (
      0 => 'search',
    ),
    'near_menu_right' => 
    array (
      0 => 'social_icons',
    ),
    'near_logo_right' => 
    array (
      0 => 'phone',
      1 => 'email',
    ),
  ),
  'header-classic-elements-near_logo-custom-icon-color' => '',
  'header-classic-elements-near_logo-custom-icon-size' => 16,
  'header-classic-elements-near_logo-font_color' => '#333333',
  'header-classic-elements-near_logo-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => '13',
  ),
  'header-classic-elements-near_logo_left-padding' => '0px 0px 0px 0px',
  'header-classic-elements-near_logo_right-padding' => '0px 0px 0px 0px',
  'header-classic-elements-near_menu-custom-icon-color' => '',
  'header-classic-elements-near_menu-custom-icon-size' => 16,
  'header-classic-elements-near_menu-font_color' => '#333333',
  'header-classic-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => '13',
  ),
  'header-classic-elements-near_menu_right-padding' => '0px 0px 0px 40px',
  'header-classic-height' => '180px',
  'header-classic-is_fullwidth' => '0',
  'header-classic-logo-position' => 'left',
  'header-classic-menu-bg-color' => 'rgba(0,0,0,1)',
  'header-classic-menu-bg-style' => 'solid',
  'header-classic-menu-margin' => '0px 0px',
  'header-classic-menu-position' => 'left',
  'header-classic-show_elements' => '1',
  'header-classic-side-padding' => '30px 30px',
  'header-classic-switch_paddings' => '0px',
  'header-classic_mobile_paddings' => '0px 0px',
  'header-decoration' => 'shadow',
  'header-decoration-color' => 'rgba(221,51,51,1)',
  'header-elements-button-1-bg' => 'accent',
  'header-elements-button-1-bg-color' => '#ffffff',
  'header-elements-button-1-bg-gradient' => '135deg|#ffffff 30%|#000000 100%',
  'header-elements-button-1-border-color' => 'accent',
  'header-elements-button-1-border-color-mono' => '#ffffff',
  'header-elements-button-1-border_radius' => '0px',
  'header-elements-button-1-border_width' => '1px',
  'header-elements-button-1-choose-icon' => '',
  'header-elements-button-1-first-header-switch' => 'near_logo',
  'header-elements-button-1-hover-bg' => 'accent',
  'header-elements-button-1-hover-bg-color' => '#ffffff',
  'header-elements-button-1-hover-bg-gradient' => '135deg|#ffffff 30%|#000000 100%',
  'header-elements-button-1-hover-border-color' => 'accent',
  'header-elements-button-1-hover-border-color-mono' => '#ffffff',
  'header-elements-button-1-hover-icon-color' => 'color',
  'header-elements-button-1-hover-icon-color-gradient' => '90deg|#ffffff 30%|#000000 100%',
  'header-elements-button-1-hover-icon-color-mono' => '#ffffff',
  'header-elements-button-1-icon' => false,
  'header-elements-button-1-icon-color' => 'color',
  'header-elements-button-1-icon-color-gradient' => '90deg|#ffffff 30%|#000000 100%',
  'header-elements-button-1-icon-color-mono' => '#ffffff',
  'header-elements-button-1-icon-position' => 'right',
  'header-elements-button-1-icon-size' => 14,
  'header-elements-button-1-icon_gap' => '5px',
  'header-elements-button-1-name' => 'Button',
  'header-elements-button-1-on-desktops' => 'show',
  'header-elements-button-1-padding' => '10px 20px 10px 20px',
  'header-elements-button-1-second-header-switch' => 'in_menu',
  'header-elements-button-1-smooth-scroll' => false,
  'header-elements-button-1-target' => false,
  'header-elements-button-1-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => '14',
  ),
  'header-elements-button-1-url' => '',
  'header-elements-button-2-bg' => 'accent',
  'header-elements-button-2-bg-color' => '#ffffff',
  'header-elements-button-2-bg-gradient' => '135deg|#ffffff 30%|#000000 100%',
  'header-elements-button-2-border-color' => 'accent',
  'header-elements-button-2-border-color-mono' => '#ffffff',
  'header-elements-button-2-border_radius' => '0px',
  'header-elements-button-2-border_width' => '1px',
  'header-elements-button-2-choose-icon' => '',
  'header-elements-button-2-first-header-switch' => 'near_logo',
  'header-elements-button-2-hover-bg' => 'accent',
  'header-elements-button-2-hover-bg-color' => '#ffffff',
  'header-elements-button-2-hover-bg-gradient' => '135deg|#ffffff 30%|#000000 100%',
  'header-elements-button-2-hover-border-color' => 'accent',
  'header-elements-button-2-hover-border-color-mono' => '#ffffff',
  'header-elements-button-2-hover-icon-color' => 'color',
  'header-elements-button-2-hover-icon-color-gradient' => '90deg|#ffffff 30%|#000000 100%',
  'header-elements-button-2-hover-icon-color-mono' => '#ffffff',
  'header-elements-button-2-icon' => false,
  'header-elements-button-2-icon-color' => 'color',
  'header-elements-button-2-icon-color-gradient' => '90deg|#ffffff 30%|#000000 100%',
  'header-elements-button-2-icon-color-mono' => '#ffffff',
  'header-elements-button-2-icon-position' => 'right',
  'header-elements-button-2-icon-size' => 14,
  'header-elements-button-2-icon_gap' => '5px',
  'header-elements-button-2-name' => 'Button',
  'header-elements-button-2-on-desktops' => 'show',
  'header-elements-button-2-padding' => '10px 20px 10px 20px',
  'header-elements-button-2-second-header-switch' => 'in_menu',
  'header-elements-button-2-smooth-scroll' => false,
  'header-elements-button-2-target' => false,
  'header-elements-button-2-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => '14',
  ),
  'header-elements-button-2-url' => '',
  'header-elements-contact-address-caption' => '8500 Beverly Boulevard Los Angeles, CA 90048',
  'header-elements-contact-address-custom-icon' => 'the7-mw-icon-address-bold',
  'header-elements-contact-address-first-header-switch' => 'top_bar_left',
  'header-elements-contact-address-icon' => 'custom',
  'header-elements-contact-address-on-desktops' => 'show',
  'header-elements-contact-address-second-header-switch' => 'in_menu',
  'header-elements-contact-address-url' => '',
  'header-elements-contact-clock-caption' => 'Monday – Friday 10 AM – 8 PM',
  'header-elements-contact-clock-custom-icon' => 'the7-mw-icon-clock-bold',
  'header-elements-contact-clock-first-header-switch' => 'near_logo',
  'header-elements-contact-clock-icon' => 'custom',
  'header-elements-contact-clock-on-desktops' => 'show',
  'header-elements-contact-clock-second-header-switch' => 'in_menu',
  'header-elements-contact-clock-url' => '',
  'header-elements-contact-email-caption' => 'sales@yoursite.com',
  'header-elements-contact-email-custom-icon' => 'the7-mw-icon-mail-bold',
  'header-elements-contact-email-first-header-switch' => 'near_logo',
  'header-elements-contact-email-icon' => 'custom',
  'header-elements-contact-email-on-desktops' => 'show',
  'header-elements-contact-email-second-header-switch' => 'in_menu',
  'header-elements-contact-email-url' => '',
  'header-elements-contact-multipurpose_1-caption' => '',
  'header-elements-contact-multipurpose_1-custom-icon' => '',
  'header-elements-contact-multipurpose_1-first-header-switch' => 'near_logo',
  'header-elements-contact-multipurpose_1-icon' => 'custom',
  'header-elements-contact-multipurpose_1-on-desktops' => 'show',
  'header-elements-contact-multipurpose_1-second-header-switch' => 'in_menu',
  'header-elements-contact-multipurpose_1-url' => '',
  'header-elements-contact-multipurpose_2-caption' => '',
  'header-elements-contact-multipurpose_2-custom-icon' => '',
  'header-elements-contact-multipurpose_2-first-header-switch' => 'near_logo',
  'header-elements-contact-multipurpose_2-icon' => 'custom',
  'header-elements-contact-multipurpose_2-on-desktops' => 'show',
  'header-elements-contact-multipurpose_2-second-header-switch' => 'in_menu',
  'header-elements-contact-multipurpose_2-url' => '',
  'header-elements-contact-multipurpose_3-caption' => '',
  'header-elements-contact-multipurpose_3-custom-icon' => '',
  'header-elements-contact-multipurpose_3-first-header-switch' => 'near_logo',
  'header-elements-contact-multipurpose_3-icon' => 'custom',
  'header-elements-contact-multipurpose_3-on-desktops' => 'show',
  'header-elements-contact-multipurpose_3-second-header-switch' => 'in_menu',
  'header-elements-contact-multipurpose_3-url' => '',
  'header-elements-contact-multipurpose_4-caption' => '',
  'header-elements-contact-multipurpose_4-custom-icon' => '',
  'header-elements-contact-multipurpose_4-first-header-switch' => 'near_logo',
  'header-elements-contact-multipurpose_4-icon' => 'custom',
  'header-elements-contact-multipurpose_4-on-desktops' => 'show',
  'header-elements-contact-multipurpose_4-second-header-switch' => 'in_menu',
  'header-elements-contact-multipurpose_4-url' => '',
  'header-elements-contact-phone-caption' => '011 322 44 56',
  'header-elements-contact-phone-custom-icon' => 'the7-mw-icon-phone-bold',
  'header-elements-contact-phone-first-header-switch' => 'top_bar_left',
  'header-elements-contact-phone-icon' => 'custom',
  'header-elements-contact-phone-on-desktops' => 'show',
  'header-elements-contact-phone-second-header-switch' => 'in_menu',
  'header-elements-contact-phone-url' => '',
  'header-elements-contact-skype-caption' => 'Your_Skype',
  'header-elements-contact-skype-custom-icon' => 'the7-mw-icon-skype-bold',
  'header-elements-contact-skype-first-header-switch' => 'near_logo',
  'header-elements-contact-skype-icon' => 'custom',
  'header-elements-contact-skype-on-desktops' => 'show',
  'header-elements-contact-skype-second-header-switch' => 'in_menu',
  'header-elements-contact-skype-url' => '',
  'header-elements-login-caption' => 'Login',
  'header-elements-login-custom-icon' => 'the7-mw-icon-login-bold',
  'header-elements-login-first-header-switch' => 'near_logo',
  'header-elements-login-icon' => 'custom',
  'header-elements-login-logout_url' => '',
  'header-elements-login-on-desktops' => 'show',
  'header-elements-login-second-header-switch' => 'in_menu',
  'header-elements-login-url' => 'http://themeforest.net',
  'header-elements-login-use_logout_url' => false,
  'header-elements-logout-caption' => 'Logout',
  'header-elements-menu-first-header-switch' => 'near_logo',
  'header-elements-menu-icon' => 'custom',
  'header-elements-menu-on-desktops' => 'show',
  'header-elements-menu-second-header-switch' => 'hidden',
  'header-elements-menu-style' => 'dropdown',
  'header-elements-menu-style-first-switch' => 'dropdown',
  'header-elements-menu-style-second-switch' => 'dropdown',
  'header-elements-menu2-first-header-switch' => 'near_logo',
  'header-elements-menu2-icon' => 'custom',
  'header-elements-menu2-on-desktops' => 'show',
  'header-elements-menu2-second-header-switch' => 'in_menu',
  'header-elements-menu2-style' => 'dropdown',
  'header-elements-menu2-style-first-switch' => 'dropdown',
  'header-elements-menu2-style-second-switch' => 'dropdown',
  'header-elements-menu2_custom-icon' => 'the7-mw-icon-dropdown-menu-bold',
  'header-elements-menu_custom-icon' => 'the7-mw-icon-dropdown-menu-bold',
  'header-elements-search-by' => 'general',
  'header-elements-search-caption' => '',
  'header-elements-search-first-header-switch' => 'near_logo',
  'header-elements-search-icon' => 'custom',
  'header-elements-search-input-caption' => 'Type and hit enter …',
  'header-elements-search-on-desktops' => 'show',
  'header-elements-search-second-header-switch' => 'near_logo',
  'header-elements-search_custom-icon' => 'the7-mw-icon-search-bold',
  'header-elements-soc_icons' => 
  array (
    1 => 
    array (
      'icon' => 'facebook',
      'url' => '/',
    ),
    2 => 
    array (
      'icon' => 'twitter',
      'url' => '/',
    ),
    3 => 
    array (
      'icon' => 'instagram',
      'url' => '/',
    ),
    4 => 
    array (
      'icon' => 'you-tube',
      'url' => '/',
    ),
  ),
  'header-elements-soc_icons-bg' => 'accent',
  'header-elements-soc_icons-bg-color' => 'rgba(255,255,255,1)',
  'header-elements-soc_icons-bg-gradient' => '135deg|#ffffff 30%|#000000 100%',
  'header-elements-soc_icons-bg-size' => '26px',
  'header-elements-soc_icons-border' => 'disabled',
  'header-elements-soc_icons-border-color' => 'rgba(255,255,255,1)',
  'header-elements-soc_icons-color' => '#ffffff',
  'header-elements-soc_icons-first-header-switch' => 'top_bar_right',
  'header-elements-soc_icons-hover-bg' => 'color',
  'header-elements-soc_icons-hover-bg-color' => '#ffffff',
  'header-elements-soc_icons-hover-bg-gradient' => '135deg|#ffffff 30%|#000000 100%',
  'header-elements-soc_icons-hover-border' => 'disabled',
  'header-elements-soc_icons-hover-border-color' => 'rgba(255,255,255,1)',
  'header-elements-soc_icons-hover-color' => '#d8b280',
  'header-elements-soc_icons-on-desktops' => 'show',
  'header-elements-soc_icons-second-header-switch' => 'in_menu',
  'header-elements-soc_icons-size' => '16px',
  'header-elements-soc_icons_border_radius' => '100px',
  'header-elements-soc_icons_border_width' => '0px',
  'header-elements-soc_icons_gap' => 4,
  'header-elements-text' => 'Some call to action text goes here!',
  'header-elements-text-2' => 'Some call to action text goes here!',
  'header-elements-text-2-first-header-switch' => 'near_logo',
  'header-elements-text-2-on-desktops' => 'show',
  'header-elements-text-2-second-header-switch' => 'in_menu',
  'header-elements-text-3' => 'Some call to action text goes here!',
  'header-elements-text-3-first-header-switch' => 'near_logo',
  'header-elements-text-3-on-desktops' => 'show',
  'header-elements-text-3-second-header-switch' => 'in_menu',
  'header-elements-text-4' => '',
  'header-elements-text-4-first-header-switch' => 'near_logo',
  'header-elements-text-4-on-desktops' => 'show',
  'header-elements-text-4-second-header-switch' => 'in_menu',
  'header-elements-text-5' => '',
  'header-elements-text-5-first-header-switch' => 'near_logo',
  'header-elements-text-5-on-desktops' => 'show',
  'header-elements-text-5-second-header-switch' => 'in_menu',
  'header-elements-text-first-header-switch' => 'near_logo',
  'header-elements-text-on-desktops' => 'show',
  'header-elements-text-second-header-switch' => 'in_menu',
  'header-elements-woocommerce_cart-caption' => '',
  'header-elements-woocommerce_cart-counter-bg' => 'accent',
  'header-elements-woocommerce_cart-counter-bg-color' => '#000000',
  'header-elements-woocommerce_cart-counter-bg-gradient' => '90deg|#ffffff 30%|#000000 100%',
  'header-elements-woocommerce_cart-counter-color' => '#ffffff',
  'header-elements-woocommerce_cart-counter-style' => 'round',
  'header-elements-woocommerce_cart-custom-icon' => 'the7-mw-icon-cart-bold',
  'header-elements-woocommerce_cart-first-header-switch' => 'near_logo',
  'header-elements-woocommerce_cart-icon' => 'custom',
  'header-elements-woocommerce_cart-on-desktops' => 'show',
  'header-elements-woocommerce_cart-second-header-switch' => 'near_logo',
  'header-elements-woocommerce_cart-show_counter' => 'allways',
  'header-elements-woocommerce_cart-show_sub_cart' => '1',
  'header-elements-woocommerce_cart-show_subtotal' => '1',
  'header-elements-woocommerce_cart-sub_cart-bg-color' => 'rgba(255,255,255,1)',
  'header-elements-woocommerce_cart-sub_cart-bg-width' => 280,
  'header-elements-woocommerce_cart-sub_cart-font-color' => '#3a3a3a',
  'header-floating_navigation-active_item-font-color' => '#ffffff',
  'header-floating_navigation-active_item-font-gradient' => '90deg|#ffffff 30%|#000000 100%',
  'header-floating_navigation-bg-color' => 'rgba(255,255,255,1)',
  'header-floating_navigation-bg-image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-floating_navigation-bg-is_fullscreen' => false,
  'header-floating_navigation-decoration' => 'shadow',
  'header-floating_navigation-decoration-color' => 'rgba(221,51,51,1)',
  'header-floating_navigation-font-active' => 'default',
  'header-floating_navigation-font-color' => '#ffffff',
  'header-floating_navigation-font-hover' => 'default',
  'header-floating_navigation-font-normal' => 'default',
  'header-floating_navigation-height' => '70px',
  'header-floating_navigation-hover-font-color' => '#ffffff',
  'header-floating_navigation-hover-font-gradient' => '90deg|#ffffff 30%|#000000 100%',
  'header-floating_navigation-show_after' => '160px',
  'header-floating_navigation-style' => 'slide',
  'header-floating_navigation-top-bar' => false,
  'header-inline-elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'phone',
      1 => 'working_hours',
    ),
    'top_bar_right' => 
    array (
      0 => 'social_icons',
    ),
    'near_menu_right' => 
    array (
      0 => 'cart',
      1 => 'search',
    ),
  ),
  'header-inline-elements-near_menu-custom-icon-color' => '',
  'header-inline-elements-near_menu-custom-icon-size' => 16,
  'header-inline-elements-near_menu-font_color' => '#ffffff',
  'header-inline-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => '13',
  ),
  'header-inline-elements-near_menu_right-padding' => '0px 0px 0px 2px',
  'header-inline-height' => '116px',
  'header-inline-is_fullwidth' => '0',
  'header-inline-menu-position' => 'justify',
  'header-inline-show_elements' => '1',
  'header-inline-side-padding' => '50px 50px',
  'header-inline-switch_paddings' => '778px',
  'header-inline_mobile_paddings' => '20px 20px',
  'header-layout' => 'split',
  'header-logo-padding' => '0px 30px 0px 30px',
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin14r.header-logo-hd.png?w=114&h=114',
    1 => 0,
  ),
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin14r.header-logo-regular.png?w=57&h=57',
    1 => 0,
  ),
  'header-mega-menu-desc-font-color' => '#3a3a3a',
  'header-mega-menu-desc-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => '13',
  ),
  'header-mega-menu-items-padding' => '9px 10px 9px 10px',
  'header-mega-menu-submenu-bg-padding' => '20px 10px 20px 10px',
  'header-mega-menu-submenu-column-padding' => '0px 10px 0px 10px',
  'header-mega-menu-submenu-column-width' => '260px',
  'header-mega-menu-title-active_item-font-color' => '#ffffff',
  'header-mega-menu-title-active_item-font-color-style' => 'accent',
  'header-mega-menu-title-active_item-font-gradient' => '90deg|#8224e3 30%|#eeee22 100%',
  'header-mega-menu-title-font-color' => '#3a3a3a',
  'header-mega-menu-title-hover-font-color' => '#ffffff',
  'header-mega-menu-title-hover-font-color-style' => 'accent',
  'header-mega-menu-title-hover-font-gradient' => '90deg|#1e73be 30%|#eeee22 99%',
  'header-mega-menu-title-icon-size' => 16,
  'header-mega-menu-title-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => '16',
    'text_transform' => 'none',
  ),
  'header-mega-menu-widget-accent-color' => '',
  'header-mega-menu-widget-font-color' => '#3a3a3a',
  'header-mega-menu-widget-title-color' => '#3a3a3a',
  'header-menu-active_item-font-color' => '#ffffff',
  'header-menu-active_item-font-color-style' => 'accent',
  'header-menu-active_item-font-gradient' => '90deg|#ffffff 30%|#000000 100%',
  'header-menu-close_icon-size' => 'fade_medium',
  'header-menu-decoration-other-active-color' => 'rgba(255,255,255,0.15)',
  'header-menu-decoration-other-active-color-style' => 'accent',
  'header-menu-decoration-other-active-gradient' => '135deg|rgba(255,255,255,0.15) 30%|rgba(0,0,0,0.15) 100%',
  'header-menu-decoration-other-active-line' => '0',
  'header-menu-decoration-other-active-line-color' => 'rgba(130,36,227,0.3)',
  'header-menu-decoration-other-active-line-color-style' => 'color',
  'header-menu-decoration-other-active-line-gradient' => '135deg|rgba(221,51,51,0.3) 30%|rgba(129,215,66,0.3) 100%',
  'header-menu-decoration-other-active-line-opacity' => 30,
  'header-menu-decoration-other-active-opacity' => 15,
  'header-menu-decoration-other-active-style' => 'background',
  'header-menu-decoration-other-border-radius' => 3,
  'header-menu-decoration-other-hover-color' => 'rgba(255,255,255,0.15)',
  'header-menu-decoration-other-hover-color-style' => 'accent',
  'header-menu-decoration-other-hover-gradient' => '135deg|rgba(255,255,255,0.15) 30%|rgba(0,0,0,0.15) 100%',
  'header-menu-decoration-other-hover-line' => '0',
  'header-menu-decoration-other-hover-line-color' => 'rgba(221,51,51,0.23)',
  'header-menu-decoration-other-hover-line-color-style' => 'gradient',
  'header-menu-decoration-other-hover-line-gradient' => '135deg|rgba(255,255,255,0.23) 30%|rgba(0,0,0,0.23) 100%',
  'header-menu-decoration-other-hover-line-opacity' => 23,
  'header-menu-decoration-other-hover-style' => 'background',
  'header-menu-decoration-other-line_size' => '2px',
  'header-menu-decoration-other-links-is_justified' => '1',
  'header-menu-decoration-other-opacity' => 15,
  'header-menu-decoration-style' => 'underline',
  'header-menu-decoration-underline-color' => '#ffffff',
  'header-menu-decoration-underline-color-style' => 'accent',
  'header-menu-decoration-underline-direction' => 'upwards',
  'header-menu-decoration-underline-gradient' => '135deg|#ffffff 30%|#000000 100%',
  'header-menu-decoration-underline-line_size' => '2px',
  'header-menu-dividers-color' => 'rgba(130,36,227,1)',
  'header-menu-dividers-height' => '20px',
  'header-menu-dividers-height-style' => 'custom',
  'header-menu-dividers-surround' => '0',
  'header-menu-font-color' => '#333333',
  'header-menu-hover-font-color' => '#ffffff',
  'header-menu-hover-font-color-style' => 'accent',
  'header-menu-hover-font-gradient' => '90deg|#8224e3 30%|#751257 100%',
  'header-menu-icon-size' => 14,
  'header-menu-item-margin' => '0px 15px 0px 15px',
  'header-menu-item-padding' => '5px 0px 5px 0px',
  'header-menu-item-surround_margins-custom-margin' => '30px',
  'header-menu-item-surround_margins-style' => 'disabled',
  'header-menu-show_dividers' => '0',
  'header-menu-show_next_lvl_icons' => false,
  'header-menu-submenu-active-bg-color' => 'rgba(58,58,58,0.07)',
  'header-menu-submenu-active-bg-color-style' => 'color',
  'header-menu-submenu-active-bg-gradient' => '90deg|#81d742 30%|#eeee22 100%',
  'header-menu-submenu-active-bg-opacity' => 7,
  'header-menu-submenu-active-font-color' => '#ffffff',
  'header-menu-submenu-active-font-color-style' => 'accent',
  'header-menu-submenu-active-font-gradient' => '90deg|#ffffff 30%|#000000 100%',
  'header-menu-submenu-bg-color' => 'rgba(255,255,255,1)',
  'header-menu-submenu-bg-hover' => '',
  'header-menu-submenu-bg-padding' => '9px 10px 9px 10px',
  'header-menu-submenu-bg-width' => '280px',
  'header-menu-submenu-font-color' => '#3a3a3a',
  'header-menu-submenu-hover-bg-color' => 'rgba(58,58,58,0.07)',
  'header-menu-submenu-hover-bg-color-style' => 'color',
  'header-menu-submenu-hover-bg-gradient' => '90deg|#81d742 30%|#eeee22 100%',
  'header-menu-submenu-hover-bg-opacity' => 7,
  'header-menu-submenu-hover-font-color' => '#3a3a3a',
  'header-menu-submenu-hover-font-color-style' => 'color',
  'header-menu-submenu-hover-font-gradient' => '90deg|#81d742 30%|#eeee22 100%',
  'header-menu-submenu-icon-size' => 14,
  'header-menu-submenu-item-margin' => '0px 0px 0px 0px',
  'header-menu-submenu-item-padding' => '9px 10px 9px 10px',
  'header-menu-submenu-show_next_lvl_icons' => '1',
  'header-menu-submenu-subtitle-typography' => 
  array (
    'font_family' => 'Arial:400italic',
    'font_size' => '10',
  ),
  'header-menu-submenu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => '13',
    'text_transform' => 'none',
  ),
  'header-menu-subtitle-typography' => 
  array (
    'font_family' => 'Arial:400italic',
    'font_size' => '11',
  ),
  'header-menu-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => '18',
    'text_transform' => 'uppercase',
  ),
  'header-menu_close_icon-bg-border-radius' => '0px',
  'header-menu_close_icon-bg-color' => 'rgba(255,255,255,0.75)',
  'header-menu_close_icon-caption_color' => '#000000',
  'header-menu_close_icon-caption_color-hover' => '#000000',
  'header-menu_close_icon-color' => '#000000',
  'header-menu_close_icon-hover-color' => '#000000',
  'header-menu_close_icon-margin' => '30px 30px 30px 30px',
  'header-menu_close_icon-padding' => '15px 15px 15px 15px',
  'header-menu_icon-bg-border-radius' => '0px',
  'header-menu_icon-bg-color' => 'rgba(255,255,255,0.75)',
  'header-menu_icon-bg-color-hover' => 'rgba(255,255,255,0.75)',
  'header-menu_icon-caption-padding' => '18px 15px 18px 15px',
  'header-menu_icon-caption_color' => '#000000',
  'header-menu_icon-caption_color-hover' => '#000000',
  'header-menu_icon-color' => '#000000',
  'header-menu_icon-color-hover' => '#000000',
  'header-menu_icon-elements' => 
  array (
    'below_menu' => 
    array (
      0 => 'social_icons',
      1 => 'cart',
      2 => 'search',
      3 => 'phone',
    ),
  ),
  'header-menu_icon-elements-below_menu-padding' => '30px 0px 0px 0px',
  'header-menu_icon-elements-near_menu-custom-icon-color' => '',
  'header-menu_icon-elements-near_menu-custom-icon-size' => 16,
  'header-menu_icon-elements-near_menu-font_color' => '#333333',
  'header-menu_icon-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => '14',
  ),
  'header-menu_icon-hover-bg-color' => 'rgba(255,255,255,0.75)',
  'header-menu_icon-margin' => '0px 0px 0px 0px',
  'header-menu_icon-show_elements' => '1',
  'header-menu_icon-size' => 'medium',
  'header-mixed-bg-color' => 'rgba(255,255,255,1)',
  'header-mixed-decoration' => 'shadow',
  'header-mixed-decoration-color' => 'rgba(221,153,51,1)',
  'header-mixed-floating-top-bar' => false,
  'header-mixed-sticky-bg-color' => '#000000',
  'header-mobile-first_switch-after' => '1100px',
  'header-mobile-first_switch-height' => '60px',
  'header-mobile-first_switch-layout' => 'right_center',
  'header-mobile-first_switch-logo' => 'mobile',
  'header-mobile-first_switch-side-padding' => '50px 50px',
  'header-mobile-floating_navigation' => 'sticky',
  'header-mobile-header-bg-color' => 'rgba(255,255,255,1)',
  'header-mobile-menu-align' => 'right',
  'header-mobile-menu-bg-color' => 'rgba(255,255,255,1)',
  'header-mobile-menu-bg-width' => '330px',
  'header-mobile-menu-dividers-color' => 'rgba(51,51,51,0.12)',
  'header-mobile-menu-font-color' => '#333333',
  'header-mobile-menu-font-hover-color' => '#3c3e45',
  'header-mobile-menu-font-hover-color-style' => 'accent',
  'header-mobile-menu-font-hover-gradient' => '90deg|#b78ce2 30%|#1e73be 100%',
  'header-mobile-menu-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => '18',
    'text_transform' => 'uppercase',
  ),
  'header-mobile-menu_icon-bg-border-radius' => '0px',
  'header-mobile-menu_icon-bg-color' => 'rgba(255,255,255,0)',
  'header-mobile-menu_icon-bg-color-hover' => 'rgba(255,255,255,0)',
  'header-mobile-menu_icon-bg-enable' => '0',
  'header-mobile-menu_icon-bg-hover' => '0',
  'header-mobile-menu_icon-caption-padding' => '4px 1px 4px 1px',
  'header-mobile-menu_icon-caption_color' => '#333333',
  'header-mobile-menu_icon-caption_color-hover' => '#333333',
  'header-mobile-menu_icon-color' => '#333333',
  'header-mobile-menu_icon-color-hover' => '#333333',
  'header-mobile-menu_icon-size' => 'small',
  'header-mobile-microwidgets-custom-icon-color' => '',
  'header-mobile-microwidgets-custom-icon-size' => 16,
  'header-mobile-microwidgets-font-color' => '#333333',
  'header-mobile-microwidgets-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => '13',
  ),
  'header-mobile-overlay-bg-color' => 'rgba(0,0,0,0.5)',
  'header-mobile-second_switch-after' => '778px',
  'header-mobile-second_switch-height' => '60px',
  'header-mobile-second_switch-layout' => 'right_left',
  'header-mobile-second_switch-logo' => 'mobile',
  'header-mobile-second_switch-side-padding' => '20px 20px',
  'header-mobile-submenu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => '13',
    'text_transform' => 'none',
  ),
  'header-overlay-content-padding' => '0px 0px 0px 0px',
  'header-overlay-content-position' => 'center',
  'header-overlay-content-width' => '300px',
  'header-overlay-logo-position' => 'fully_inside',
  'header-overlay-menu-items_alignment' => 'center',
  'header-overlay-menu-items_link' => 'fullwidth',
  'header-overlay-menu-position' => 'v_center',
  'header-show_floating_navigation' => '1',
  'header-side-content-padding' => '50px 0px 40px 0px',
  'header-side-elements' => 
  array (
    'below_menu' => 
    array (
      0 => 'social_icons',
      1 => 'email',
      2 => 'skype',
    ),
  ),
  'header-side-elements-below_menu-padding' => '0px 35px 0px 35px',
  'header-side-elements-near_menu-custom-icon-color' => '',
  'header-side-elements-near_menu-custom-icon-size' => 16,
  'header-side-elements-near_menu-font_color' => '#333333',
  'header-side-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => '14',
  ),
  'header-side-logo-position' => 'inside',
  'header-side-menu-items_alignment' => 'center',
  'header-side-menu-items_link' => 'fullwidth',
  'header-side-menu-position' => 'v_top',
  'header-side-menu-submenu-position' => 'down',
  'header-side-position' => 'right',
  'header-side-show_elements' => '1',
  'header-side-width' => '300px',
  'header-side_line-elements' => 
  array (
    'below_menu' => 
    array (
      0 => 'social_icons',
      1 => 'cart',
      2 => 'search',
      3 => 'phone',
    ),
  ),
  'header-side_line-elements-below_menu-padding' => '30px 0px 0px 0px',
  'header-side_line-elements-near_menu-custom-icon-color' => '',
  'header-side_line-elements-near_menu-custom-icon-size' => 16,
  'header-side_line-elements-near_menu-font_color' => '#333333',
  'header-side_line-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => '14',
  ),
  'header-side_line-show_elements' => '1',
  'header-side_line-width' => '60px',
  'header-slide_out-content-padding' => '50px 0px 50px 0px',
  'header-slide_out-logo-position' => 'fully_inside',
  'header-slide_out-menu-items_alignment' => 'center',
  'header-slide_out-menu-items_link' => 'fullwidth',
  'header-slide_out-menu-position' => 'v_top',
  'header-slide_out-overlay-animation' => 'fade',
  'header-slide_out-overlay-bg-color' => 'rgba(58,58,58,0.3)',
  'header-slide_out-overlay-bg-color-style' => 'color',
  'header-slide_out-overlay-bg-gradient' => '135deg|rgba(205,183,226,0.3) 30%|rgba(130,20,130,0.3) 100%',
  'header-slide_out-overlay-bg-opacity' => 30,
  'header-slide_out-position' => 'left',
  'header-slide_out-width' => '400px',
  'header-split-elements' => 
  array (
    'near_menu_left' => 
    array (
      0 => 'search',
    ),
    'near_menu_right' => 
    array (
      0 => 'cart',
    ),
  ),
  'header-split-elements-near_menu-custom-icon-color' => '',
  'header-split-elements-near_menu-custom-icon-size' => 16,
  'header-split-elements-near_menu-font_color' => '#333333',
  'header-split-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => '13',
  ),
  'header-split-elements-near_menu_left-padding' => '0px 0px 0px 0px',
  'header-split-elements-near_menu_right-padding' => '0px 0px 0px 0px',
  'header-split-height' => '120px',
  'header-split-is_fullwidth' => '0',
  'header-split-menu-position' => 'inside',
  'header-split-show_elements' => '1',
  'header-split-side-padding' => '50px 50px',
  'header-split-switch_paddings' => '778px',
  'header-split_mobile_paddings' => '20px 20px',
  'header-style-floating-choose_logo' => 'custom',
  'header-style-floating-logo-padding' => '0px 36px 0px 37px',
  'header-style-floating-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin14r.header-style-floating-logo-hd.png?w=88&h=88',
    1 => 0,
  ),
  'header-style-floating-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin14r.header-style-floating-logo-regular.png?w=44&h=44',
    1 => 0,
  ),
  'header-style-mixed-logo-padding' => '0px 0px 0px 0px',
  'header-style-mixed-logo_hd' => 
  array (
    0 => '',
    1 => 0,
  ),
  'header-style-mixed-logo_regular' => 
  array (
    0 => '',
    1 => 0,
  ),
  'header-style-mixed-top_line-floating-choose_logo' => 'main',
  'header-style-mixed-top_line-floating-logo-padding' => '0px 0px 0px 0px',
  'header-style-mixed-top_line-floating-logo_hd' => 
  array (
    0 => '',
    1 => 0,
  ),
  'header-style-mixed-top_line-floating-logo_regular' => 
  array (
    0 => '',
    1 => 0,
  ),
  'header-style-mobile-logo-padding' => '0px 0px 0px 0px',
  'header-style-mobile-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin14r.header-style-mobile-logo-hd.png?w=88&h=88',
    1 => 0,
  ),
  'header-style-mobile-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin14r.header-style-mobile-logo-regular.png?w=44&h=44',
    1 => 0,
  ),
  'header-style-transparent-choose_logo' => 'custom',
  'header-style-transparent-logo-padding' => '0px 30px 0px 30px',
  'header-style-transparent-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin14r.header-style-transparent-logo-hd.png?w=114&h=114',
    1 => 0,
  ),
  'header-style-transparent-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin14r.header-style-transparent-logo-regular.png?w=57&h=57',
    1 => 0,
  ),
  'header-style-transparent-mobile-logo-padding' => '0px 0px 0px 0px',
  'header-style-transparent-mobile-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin14r.header-style-transparent-mobile-logo-hd.png?w=88&h=88',
    1 => 0,
  ),
  'header-style-transparent-mobile-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin14r.header-style-transparent-mobile-logo-regular.png?w=44&h=44',
    1 => 0,
  ),
  'header-top_line-elements' => 
  array (
    'top_line_right' => 
    array (
      0 => 'cart',
      1 => 'search',
      2 => 'phone',
      3 => 'social_icons',
    ),
  ),
  'header-top_line-elements-below_menu-padding' => '35px 0px 0px 0px',
  'header-top_line-elements-in_top_line-custom-icon-color' => '',
  'header-top_line-elements-in_top_line-custom-icon-size' => 16,
  'header-top_line-elements-in_top_line-font_color' => '#333333',
  'header-top_line-elements-in_top_line-typography' => 
  array (
    'font_family' => 'Arial',
    'font_size' => '14',
  ),
  'header-top_line-elements-near_menu-custom-icon-color' => '',
  'header-top_line-elements-near_menu-custom-icon-size' => 16,
  'header-top_line-elements-near_menu-font_color' => '#333333',
  'header-top_line-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => '13',
  ),
  'header-top_line-elements-top_line-padding' => '0px 0px 0px 0px',
  'header-top_line-elements-top_line_right-padding' => '0px 0px 0px 0px',
  'header-top_line-show_elements' => '1',
  'header-top_line-side-padding' => '30px 30px',
  'header-top_line-switch_paddings' => '0px',
  'header-top_line_mobile_paddings' => '0px 0px',
  'header-transparent-mobile-first_switch-logo' => 'mobile',
  'header-transparent-mobile-second_switch-logo' => 'mobile',
  'header-transparent_bg_color' => 'rgba(255,255,255,1)',
  'header_navigation' => 'slide_out',
  'image_hover-color' => 'rgba(40,40,40,0.15)',
  'image_hover-color_gradient' => '135deg|rgba(0,0,0,0.15) 30%|rgba(48,48,48,0.15) 100%',
  'image_hover-color_mode' => 'color',
  'image_hover-opacity' => 15,
  'image_hover-project_rollover_color' => 'rgba(40,40,40,0.8)',
  'image_hover-project_rollover_color_gradient' => '135deg|rgba(106,229,230,0.8) 30%|rgba(17,144,201,0.8) 100%',
  'image_hover-project_rollover_color_mode' => 'color',
  'image_hover-project_rollover_opacity' => 80,
  'image_hover-style' => 'none',
  'input_bg_color' => 'rgba(255,255,255,1)',
  'input_border_color' => 'rgba(51,51,51,0.12)',
  'input_border_radius' => '0px',
  'input_border_width' => '1px 1px 1px 1px',
  'input_color' => '#85868c',
  'input_height' => '38px',
  'layout-menu_icon-position' => 'menu_icon_right',
  'layout-menu_icon-show_floating_logo' => '1',
  'layout-side_line-position' => 'above',
  'layout-side_line-v_position' => 'left',
  'layout-top_line-height' => '74px',
  'layout-top_line-is_fullwidth' => '1',
  'layout-top_line-is_sticky' => '1',
  'layout-top_line-logo-position' => 'left',
  'menu-mobile-microwidgets-custom-icon-color' => '',
  'menu-mobile-microwidgets-custom-icon-size' => 16,
  'menu-mobile-microwidgets-font-color' => '#333333',
  'menu-mobile-microwidgets-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => '13',
  ),
  'message_bg_color' => '',
  'message_color' => '#ffffff',
  'microwidgets-search-active-width' => '200px',
  'microwidgets-search-height' => '34px',
  'microwidgets-search-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => '14',
  ),
  'microwidgets-search-width' => '200px',
  'microwidgets-search_bg-border-color' => '#e2e2e2',
  'microwidgets-search_bg-color' => '#f4f4f4',
  'microwidgets-search_bg_border_radius' => '0px',
  'microwidgets-search_bg_border_width' => '0px',
  'microwidgets-search_custom-icon' => 'the7-mw-icon-search-bold',
  'microwidgets-search_font-color' => '#aaaaaa',
  'microwidgets-search_icon' => 'custom',
  'microwidgets-search_icon-size' => 16,
  'microwidgets-search_input-padding' => '12px 12px',
  'microwidgets-search_overlay-bg' => 'color',
  'microwidgets-search_overlay-bg-color' => 'rgba(0,0,0,0.9)',
  'microwidgets-search_overlay-bg-gradient' => '135deg|#ffffff 30%|#000000 100%',
  'microwidgets-search_style' => 'popup',
  'page_title-background-style-transparent-color_scheme' => 'light',
  'page_title-padding' => '25px 25px',
  'portfolio-breadcrumbs-text' => '',
  'portfolio-rel_projects_columns' => 
  array (
    'wide_desktop' => 4,
    'desktop' => 3,
    'laptop' => 3,
    'h_tablet' => 3,
    'v_tablet' => 2,
    'phone' => 1,
  ),
  'portfolio-rel_projects_proportions' => 
  array (
    'width' => 1,
    'height' => 1,
  ),
  'post-show_fancy_categories' => '1',
  'post-show_fancy_date' => '1',
  'preset' => 'skin14r',
  'sidebar-bg_color' => 'rgba(255,255,255,0.29)',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-decoration' => 'none',
  'sidebar-decoration_outline_color' => 'rgba(0,0,0,0.06)',
  'sidebar-distance_to_content' => '50px',
  'sidebar-divider-horizontal' => '1',
  'sidebar-divider-vertical' => '0',
  'sidebar-floating' => false,
  'sidebar-headers_color' => '#333333',
  'sidebar-primary_text_color' => '#85868c',
  'sidebar-responsiveness' => '992px',
  'sidebar-vertical_distance' => '84px',
  'sidebar-visual_style' => 'with_dividers',
  'sidebar-width' => '350px',
  'social_buttons-product' => 
  array (
    0 => 'twitter',
    1 => 'pinterest',
    2 => 'linkedin',
    3 => 'whatsapp',
    4 => 'facebook',
  ),
  'social_buttons-product-button_title' => 'Share this product',
  'social_buttons-visibility' => 'allways',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_color' => '#f3f3f3',
  'stripes-stripe_1_content_boxes_bg_color' => '#ffffff',
  'stripes-stripe_1_content_boxes_bg_opacity' => 100,
  'stripes-stripe_1_content_boxes_decoration' => 'none',
  'stripes-stripe_1_content_boxes_decoration_outline_color' => '#dd3333',
  'stripes-stripe_1_content_boxes_decoration_outline_opacity' => 100,
  'stripes-stripe_1_headers_color' => '#3a3a3a',
  'stripes-stripe_1_outline' => 'hide',
  'stripes-stripe_1_outline_color' => '#44bb70',
  'stripes-stripe_1_outline_opacity' => 100,
  'stripes-stripe_1_text_color' => '#888888',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_color' => '#333333',
  'stripes-stripe_2_content_boxes_bg_color' => '#949494',
  'stripes-stripe_2_content_boxes_bg_opacity' => 12,
  'stripes-stripe_2_content_boxes_decoration' => 'none',
  'stripes-stripe_2_content_boxes_decoration_outline_color' => '#ffffff',
  'stripes-stripe_2_content_boxes_decoration_outline_opacity' => 100,
  'stripes-stripe_2_headers_color' => '#ffffff',
  'stripes-stripe_2_outline' => 'hide',
  'stripes-stripe_2_outline_color' => '#c1edaf',
  'stripes-stripe_2_outline_opacity' => 100,
  'stripes-stripe_2_text_color' => '#949494',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin14r.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_color' => '#141414',
  'stripes-stripe_3_content_boxes_bg_color' => '#FFFFFF',
  'stripes-stripe_3_content_boxes_bg_opacity' => 17,
  'stripes-stripe_3_content_boxes_decoration' => 'none',
  'stripes-stripe_3_content_boxes_decoration_outline_color' => '#ffffff',
  'stripes-stripe_3_content_boxes_decoration_outline_opacity' => 100,
  'stripes-stripe_3_headers_color' => '#ffffff',
  'stripes-stripe_3_outline' => 'hide',
  'stripes-stripe_3_outline_color' => '#FFFFFF',
  'stripes-stripe_3_outline_opacity' => 100,
  'stripes-stripe_3_text_color' => '#f7f7f7',
  'the7_opengraph_tags' => '1',
  'top-bar-height' => '36px',
  'top-bar-transparent_bg_color' => 'rgba(0,0,0,0.5)',
  'top_bar-bg-color' => '#1a1c20',
  'top_bar-bg-image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-bg-style' => 'disabled',
  'top_bar-custom-icon-color' => '',
  'top_bar-custom-icon-size' => 16,
  'top_bar-font-color' => '#ffffff',
  'top_bar-line-color' => 'rgba(255,255,255,0.12)',
  'top_bar-line-in-transparent-header' => false,
  'top_bar-line_size' => '1px',
  'top_bar-line_style' => 'solid',
  'top_bar-padding' => '5px 50px 5px 50px',
  'top_bar-switch_paddings' => '778px',
  'top_bar-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => '13',
    'text_transform' => 'none',
  ),
  'top_bar_mobile_paddings' => '5px 20px 5px 20px',
  'wc_view_mode' => 'view_mode',
  'woocommerce-product_zoom' => '1',
  'woocommerce_cart_padding' => '70px 10px',
  'woocommerce_cart_switch' => '990px',
  'woocommerce_cart_total_width' => '50%',
  'woocommerce_display_product_info' => 'wc_btn_on_img',
  'woocommerce_hover_image' => '1',
  'woocommerce_list_switch' => '778px',
  'woocommerce_product_img_width' => '50%',
  'woocommerce_product_switch' => '778px',
  'woocommerce_rel_products_max' => 6,
  'woocommerce_shop_template_bwb_columns' => 
  array (
    'desktop' => 3,
    'h_tablet' => 3,
    'v_tablet' => 2,
    'phone' => 1,
  ),
  'woocommerce_shop_template_column_min_width' => '220px',
  'woocommerce_shop_template_columns' => 5,
  'woocommerce_shop_template_gap' => '18px',
  'woocommerce_shop_template_img_width' => '50%',
  'woocommerce_shop_template_isotope' => 'grid',
  'woocommerce_shop_template_layout_default' => 'masonry_grid_default',
  'woocommerce_shop_template_loading_effect' => 'none',
  'woocommerce_shop_template_responsiveness' => 'browser_width_based',
  'woocommerce_show_cart_icon' => '1',
  'woocommerce_show_list_desc' => '1',
  'woocommerce_show_masonry_desc' => '0',
  'woocommerce_show_product_price' => '1',
  'woocommerce_show_product_rating' => '1',
  'woocommerce_show_product_titles' => '1',
  'woocommerce_show_steps' => '1',
  'woocommerce_steps-bg_opacity' => 0,
  'woocommerce_steps_bg_color' => '#ffffff',
  'woocommerce_steps_color' => '#333333',
);