<?php $presets["wizard01"] = array (
  'advanced-speed_img_resize' => '1',
  'blog-fancy_date-style' => 'vertical',
  'blog-thumbnail_proportions' => 
  array (
    'width' => 2,
    'height' => 1,
  ),
  'blog-thumbnail_size' => 'resize',
  'bottom_bar-bg_color' => 'rgba(255,255,255,0.1)',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#ffffff',
  'bottom_bar-credits' => '1',
  'bottom_bar-enabled' => '1',
  'bottom_bar-logo-padding' => '10px 15px 10px 0px',
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/wizard01.bottom-bar-logo-hd.png?w=54&h=54',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/wizard01.bottom-bar-logo-regular.png?w=27&h=27',
    1 => 0,
  ),
  'bottom_bar-style' => 'solid_background',
  'breadcrumbs-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => 13,
    'line_height' => 23,
  ),
  'breadcrumbs_bg_color' => 'rgba(255,255,255,0.2)',
  'breadcrumbs_border_color' => 'rgba(130,36,227,0.2)',
  'breadcrumbs_border_radius' => 2,
  'breadcrumbs_border_width' => 0,
  'breadcrumbs_margin' => '8px 0px 0px 0px',
  'breadcrumbs_padding' => '0px 0px 0px 0px',
  'buttons-color' => '#81d742',
  'buttons-color_gradient' => '135deg|#13aa4a 30%|#84df31 100%',
  'buttons-color_mode' => 'accent',
  'buttons-hover_color' => '#81d742',
  'buttons-hover_color_gradient' => '135deg|#23aadd 30%|#37ce9d 100%',
  'buttons-hover_color_mode' => 'gradient',
  'buttons-l-icon-size' => 18,
  'buttons-l-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 18,
  ),
  'buttons-l_border_radius' => 1,
  'buttons-l_padding' => '16px 24px 16px 24px',
  'buttons-l_uppercase' => false,
  'buttons-m-icon-size' => 14,
  'buttons-m-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 14,
  ),
  'buttons-m_border_radius' => 1,
  'buttons-m_padding' => '12px 18px 12px 18px',
  'buttons-m_uppercase' => false,
  'buttons-s-icon-size' => 12,
  'buttons-s-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 12,
  ),
  'buttons-s_border_radius' => 1,
  'buttons-s_padding' => '8px 14px 7px 14px',
  'buttons-s_uppercase' => false,
  'buttons-style' => 'flat',
  'buttons-text_color' => '#ffffff',
  'buttons-text_color_mode' => 'color',
  'buttons-text_hover_color' => '#ffffff',
  'buttons-text_hover_color_mode' => 'color',
  'contact_form_message' => '1',
  'content-headers_color' => '#333333',
  'content-links_color' => '#1ebbf0',
  'content-primary_text_color' => '#85868c',
  'content-secondary_text_color' => '#b4b5bb',
  'custom_error_messages' => 'The message has not been sent. Please try again.',
  'custom_error_messages_validation' => 'One or more fields have an error. Please check and try again.',
  'custom_success_messages' => 'Your message has been sent.',
  'dividers-color' => 'rgba(51,51,51,0.12)',
  'filter-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 13,
  ),
  'fonts-big_size' => 15,
  'fonts-big_size_line_height' => 27,
  'fonts-font_family' => 'Roboto',
  'fonts-h1-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 44,
    'line_height' => 54,
  ),
  'fonts-h1_uppercase' => false,
  'fonts-h2-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 34,
    'line_height' => 44,
  ),
  'fonts-h2_uppercase' => false,
  'fonts-h3-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 24,
    'line_height' => 34,
  ),
  'fonts-h3_uppercase' => false,
  'fonts-h4-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 20,
    'line_height' => 30,
  ),
  'fonts-h4_uppercase' => false,
  'fonts-h5-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 16,
    'line_height' => 26,
  ),
  'fonts-h5_uppercase' => false,
  'fonts-h6-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 14,
    'line_height' => 24,
  ),
  'fonts-h6_uppercase' => false,
  'fonts-normal_size' => 14,
  'fonts-normal_size_line_height' => 25,
  'fonts-small_size' => 13,
  'fonts-small_size_line_height' => 23,
  'footer-accent_text_color' => '',
  'footer-bg_color' => 'rgba(26,28,32,1)',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-collapse_after' => 778,
  'footer-decoration' => 'none',
  'footer-decoration_outline_color' => 'rgba(129,215,66,0.96)',
  'footer-headers_color' => '#ffffff',
  'footer-padding' => '60px 25px',
  'footer-paddings-columns' => 25,
  'footer-primary_text_color' => '#85868c',
  'footer-slide-out-mode' => '0',
  'footer-style' => 'solid_background',
  'general-accent_bg_color' => '#5891e8',
  'general-accent_bg_color_gradient' => '135deg|#1ebbf0 30%|#39dfaa 100%',
  'general-accent_color_mode' => 'gradient',
  'general-album_back_button_target_page_id' => 16237,
  'general-album_meta_author' => false,
  'general-album_meta_categories' => '1',
  'general-album_meta_comments' => false,
  'general-album_meta_date' => '1',
  'general-album_meta_on' => '1',
  'general-bg_color' => 'rgba(255,255,255,1)',
  'general-bg_fixed' => false,
  'general-bg_fullscreen' => false,
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-border_radius' => 1,
  'general-box_width' => '1340px',
  'general-boxed_bg_color' => '#f7f7f7',
  'general-boxed_bg_fixed' => '1',
  'general-boxed_bg_fullscreen' => false,
  'general-boxed_bg_image' => 
  array (
    'image' => '/images/backgrounds/patterns/full/gplaypattern.jpg',
    'repeat' => 'repeat',
    'position_x' => 'left',
    'position_y' => 'top',
  ),
  'general-breadcrumbs_bg_color' => 'disabled',
  'general-breadcrumbs_color' => '#b4b5bb',
  'general-breadcrumbs_uppercase' => false,
  'general-content_boxes_bg_color' => 'rgba(247,247,247,1)',
  'general-content_boxes_decoration' => 'none',
  'general-content_boxes_decoration_outline_color' => 'rgba(0,0,0,0)',
  'general-content_width' => '1300px',
  'general-custom_css' => '',
  'general-custom_loader' => '',
  'general-filter-margin' => '0px 3px 0px 3px',
  'general-filter-padding' => '8px 14px 7px 14px',
  'general-filter_style' => 'minimal',
  'general-filter_style-material-line_size' => 2,
  'general-filter_style-minimal-border_radius' => 1,
  'general-filter_ucase' => '1',
  'general-fullscreen_overlay_color' => 'rgba(255,255,255,1)',
  'general-fullscreen_overlay_color_mode' => 'color',
  'general-fullscreen_overlay_gradient' => '135deg|#2edded 30%|#0084bb 100%',
  'general-fullscreen_overlay_opacity' => 100,
  'general-images_lazy_loading' => '1',
  'general-layout' => 'wide',
  'general-lightbox_arrow_size' => 62,
  'general-lightbox_overlay_opacity' => 85,
  'general-loader_style' => 'double_circles',
  'general-mobile_side_content_paddings' => 20,
  'general-navigation_margin' => 50,
  'general-next_prev_in_album' => '1',
  'general-page-title-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 30,
    'line_height' => 40,
  ),
  'general-page_content_margin' => '70px 70px',
  'general-portfolio_thumbnail_proportions' => 
  array (
    'width' => 2,
    'height' => 1,
  ),
  'general-portfolio_thumbnail_size' => 'resize',
  'general-rel_posts_head_title' => 'Related Posts',
  'general-rel_posts_max' => 6,
  'general-responsive' => '1',
  'general-responsive_title_height' => 70,
  'general-responsive_title_line_height' => 34,
  'general-responsive_title_size' => 24,
  'general-show_back_button_in_album' => '1',
  'general-show_breadcrumbs' => '1',
  'general-show_rel_posts' => '1',
  'general-show_titles' => '1',
  'general-side_content_paddings' => 50,
  'general-smooth_scroll' => 'off',
  'general-spinner_color' => 'rgba(51,51,51,0.3)',
  'general-switch_content_paddings' => 778,
  'general-title_align' => 'center',
  'general-title_bg_color' => 'rgba(247,247,247,1)',
  'general-title_bg_fullscreen' => false,
  'general-title_bg_gradient' => '0deg|#4a66d6 30%|#12b4ea 100%',
  'general-title_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'general-title_bg_mode' => 'background',
  'general-title_bg_overlay' => false,
  'general-title_bg_parallax' => '0',
  'general-title_color' => '#333333',
  'general-title_decoration' => 'none',
  'general-title_decoration_line_color' => 'rgba(51,51,51,0.11)',
  'general-title_decoration_line_height' => 5,
  'general-title_decoration_line_style' => 'dashed',
  'general-title_decoration_outline_color' => 'rgba(30,115,190,0)',
  'general-title_decoration_outline_height' => 1,
  'general-title_decoration_outline_style' => 'solid',
  'general-title_enable_bg_img' => 'disabled',
  'general-title_height' => 180,
  'general-title_overlay_color' => 'rgba(0,0,0,0.5)',
  'general-title_responsive_breadcrumbs' => '1',
  'general-title_scroll_effect' => 'default',
  'general-title_uppercase' => '1',
  'general-titles-responsiveness-switch' => 778,
  'general-titles_responsiveness' => '1',
  'header-background' => 'normal',
  'header-bg-color' => 'rgba(255,255,255,1)',
  'header-bg-image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg-is_fixed' => false,
  'header-bg-is_fullscreen' => false,
  'header-classic-elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'phone',
      1 => 'address',
    ),
    'top_bar_right' => 
    array (
      0 => 'social_icons',
    ),
    'near_menu_right' => 
    array (
      0 => 'cart',
      1 => 'search',
    ),
  ),
  'header-classic-elements-near_logo-font_color' => '#333333',
  'header-classic-elements-near_logo-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => 13,
  ),
  'header-classic-elements-near_logo_left-padding' => '0px 0px 0px 0px',
  'header-classic-elements-near_logo_right-padding' => '0px 0px 0px 0px',
  'header-classic-elements-near_menu-font_color' => '#333333',
  'header-classic-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 13,
  ),
  'header-classic-elements-near_menu_right-padding' => '0px 0px 0px 30px',
  'header-classic-height' => 160,
  'header-classic-icons_style' => 'bold',
  'header-classic-is_fullwidth' => '0',
  'header-classic-logo-position' => 'center',
  'header-classic-menu-bg-color' => 'rgba(0,0,0,1)',
  'header-classic-menu-bg-style' => 'disabled',
  'header-classic-menu-margin' => '-25px 0px',
  'header-classic-menu-position' => 'center',
  'header-classic-show_elements' => '1',
  'header-decoration' => 'shadow',
  'header-decoration-color' => 'rgba(51,51,51,0.11)',
  'header-elements-contact-address-caption' => '8500 Beverly Boulevard Los Angeles, CA 90048',
  'header-elements-contact-address-first-header-switch' => 'top_bar_left',
  'header-elements-contact-address-icon' => '1',
  'header-elements-contact-address-on-desktops' => 'show',
  'header-elements-contact-address-second-header-switch' => 'hidden',
  'header-elements-contact-clock-caption' => 'Monday – Friday 10 AM – 8 PM',
  'header-elements-contact-clock-first-header-switch' => 'in_menu',
  'header-elements-contact-clock-icon' => '1',
  'header-elements-contact-clock-on-desktops' => 'show',
  'header-elements-contact-clock-second-header-switch' => 'in_menu',
  'header-elements-contact-email-caption' => 'sales@yoursite.com',
  'header-elements-contact-email-first-header-switch' => 'in_menu',
  'header-elements-contact-email-icon' => '1',
  'header-elements-contact-email-on-desktops' => 'show',
  'header-elements-contact-email-second-header-switch' => 'in_menu',
  'header-elements-contact-phone-caption' => '011 322 44 56',
  'header-elements-contact-phone-first-header-switch' => 'in_menu',
  'header-elements-contact-phone-icon' => '1',
  'header-elements-contact-phone-on-desktops' => 'show',
  'header-elements-contact-phone-second-header-switch' => 'in_menu',
  'header-elements-contact-skype-caption' => 'Your_Skype',
  'header-elements-contact-skype-first-header-switch' => 'near_logo',
  'header-elements-contact-skype-icon' => '1',
  'header-elements-contact-skype-on-desktops' => 'show',
  'header-elements-contact-skype-second-header-switch' => 'in_top_bar',
  'header-elements-edd_cart-sub_cart-bg-color' => 'rgba(255,255,255,1)',
  'header-elements-edd_cart-sub_cart-bg-width' => 280,
  'header-elements-edd_cart-sub_cart-font-color' => '#333333',
  'header-elements-login-caption' => 'Login',
  'header-elements-login-first-header-switch' => 'near_logo',
  'header-elements-login-icon' => '1',
  'header-elements-login-logout_url' => '',
  'header-elements-login-on-desktops' => 'show',
  'header-elements-login-second-header-switch' => 'in_menu',
  'header-elements-login-url' => 'http://themeforest.net',
  'header-elements-login-use_logout_url' => false,
  'header-elements-logout-caption' => 'Logout',
  'header-elements-menu-first-header-switch' => 'near_logo',
  'header-elements-menu-on-desktops' => 'show',
  'header-elements-menu-second-header-switch' => 'in_menu',
  'header-elements-menu-style' => 'list',
  'header-elements-menu-style-first-switch' => 'list',
  'header-elements-menu-style-second-switch' => 'list',
  'header-elements-menu2-first-header-switch' => 'near_logo',
  'header-elements-menu2-on-desktops' => 'show',
  'header-elements-menu2-second-header-switch' => 'in_menu',
  'header-elements-menu2-style' => 'dropdown',
  'header-elements-menu2-style-first-switch' => 'dropdown',
  'header-elements-menu2-style-second-switch' => 'dropdown',
  'header-elements-near_logo-font_color' => '#333333',
  'header-elements-near_logo-font_family' => 'Roboto',
  'header-elements-near_logo-font_size' => 16,
  'header-elements-near_menu-font_color' => '#333333',
  'header-elements-near_menu-font_family' => 'Roboto',
  'header-elements-near_menu-font_size' => 14,
  'header-elements-search-caption' => 'Search',
  'header-elements-search-first-header-switch' => 'near_logo',
  'header-elements-search-icon' => 'default',
  'header-elements-search-on-desktops' => 'show',
  'header-elements-search-second-header-switch' => 'near_logo',
  'header-elements-soc_icons' => 
  array (
    0 => 
    array (
      'icon' => 'facebook',
      'url' => '/',
    ),
    1 => 
    array (
      'icon' => 'twitter',
      'url' => '/',
    ),
    2 => 
    array (
      'icon' => 'dribbble',
      'url' => '/',
    ),
  ),
  'header-elements-soc_icons-bg' => 'disabled',
  'header-elements-soc_icons-bg-color' => '#ffffff',
  'header-elements-soc_icons-bg-gradient' => '135deg|#ffffff 30%|#000000 100%',
  'header-elements-soc_icons-bg-size' => 26,
  'header-elements-soc_icons-border' => 'accent',
  'header-elements-soc_icons-border-color' => 'rgba(255,255,255,1)',
  'header-elements-soc_icons-color' => '',
  'header-elements-soc_icons-first-header-switch' => 'in_menu',
  'header-elements-soc_icons-hover-bg' => 'accent',
  'header-elements-soc_icons-hover-bg-color' => 'rgba(21,191,230,1)',
  'header-elements-soc_icons-hover-bg-gradient' => '135deg|#ffffff 30%|#000000 100%',
  'header-elements-soc_icons-hover-border' => 'disabled',
  'header-elements-soc_icons-hover-border-color' => 'rgba(255,255,255,1)',
  'header-elements-soc_icons-hover-color' => '#ffffff',
  'header-elements-soc_icons-on-desktops' => 'show',
  'header-elements-soc_icons-second-header-switch' => 'in_menu',
  'header-elements-soc_icons-size' => 16,
  'header-elements-soc_icons_border_radius' => 100,
  'header-elements-soc_icons_border_width' => 2,
  'header-elements-soc_icons_gap' => 4,
  'header-elements-text' => 'Some call to action text goes here!',
  'header-elements-text-2' => 'Some call to action text goes here!',
  'header-elements-text-2-first-header-switch' => 'near_logo',
  'header-elements-text-2-on-desktops' => 'show',
  'header-elements-text-2-second-header-switch' => 'in_menu',
  'header-elements-text-3' => 'Some call to action text goes here!',
  'header-elements-text-3-first-header-switch' => 'near_logo',
  'header-elements-text-3-on-desktops' => 'show',
  'header-elements-text-3-second-header-switch' => 'in_menu',
  'header-elements-text-first-header-switch' => 'near_logo',
  'header-elements-text-on-desktops' => 'show',
  'header-elements-text-second-header-switch' => 'in_menu',
  'header-elements-woocommerce_cart-caption' => '',
  'header-elements-woocommerce_cart-counter-bg' => 'accent',
  'header-elements-woocommerce_cart-counter-bg-color' => '#000000',
  'header-elements-woocommerce_cart-counter-bg-gradient' => '90deg|#37a0fe 30%|#6b5ffd 100%',
  'header-elements-woocommerce_cart-counter-color' => '#ffffff',
  'header-elements-woocommerce_cart-counter-style' => 'round',
  'header-elements-woocommerce_cart-first-header-switch' => 'near_logo',
  'header-elements-woocommerce_cart-icon' => '1',
  'header-elements-woocommerce_cart-on-desktops' => 'show',
  'header-elements-woocommerce_cart-second-header-switch' => 'near_logo',
  'header-elements-woocommerce_cart-show_counter' => 'allways',
  'header-elements-woocommerce_cart-show_sub_cart' => '1',
  'header-elements-woocommerce_cart-show_subtotal' => '1',
  'header-elements-woocommerce_cart-sub_cart-bg-color' => 'rgba(255,255,255,1)',
  'header-elements-woocommerce_cart-sub_cart-bg-width' => 280,
  'header-elements-woocommerce_cart-sub_cart-font-color' => '#333333',
  'header-floating_navigation-bg-color' => 'rgba(255,255,255,1)',
  'header-floating_navigation-decoration' => 'shadow',
  'header-floating_navigation-decoration-color' => 'rgba(51,51,51,0.11)',
  'header-floating_navigation-height' => 60,
  'header-floating_navigation-show_after' => 150,
  'header-floating_navigation-style' => 'fade',
  'header-inline-elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'phone',
      1 => 'address',
    ),
    'top_bar_right' => 
    array (
      0 => 'social_icons',
    ),
    'near_menu_right' => 
    array (
      0 => 'cart',
      1 => 'search',
    ),
  ),
  'header-inline-elements-near_menu-font_color' => '#333333',
  'header-inline-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 13,
  ),
  'header-inline-elements-near_menu_right-padding' => '0px 0px 0px 30px',
  'header-inline-height' => 100,
  'header-inline-icons_style' => 'bold',
  'header-inline-is_fullwidth' => '0',
  'header-inline-menu-position' => 'right',
  'header-inline-show_elements' => '1',
  'header-layout' => 'inline',
  'header-logo-padding' => '0px 5px 0px 0px',
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/wizard01.header-logo-hd.png?w=114&h=114',
    1 => 0,
  ),
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/wizard01.header-logo-regular.png?w=57&h=57',
    1 => 0,
  ),
  'header-mega-menu-desc-font-color' => '#333333',
  'header-mega-menu-desc-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => 13,
  ),
  'header-mega-menu-title-active_item-font-color-style' => 'accent',
  'header-mega-menu-title-font-color' => '#333333',
  'header-mega-menu-title-hover-font-color-style' => 'accent',
  'header-mega-menu-title-icon-size' => 16,
  'header-mega-menu-title-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 16,
    'text_transform' => 'none',
  ),
  'header-mega-menu-widget-accent-color' => '',
  'header-mega-menu-widget-font-color' => '#333333',
  'header-mega-menu-widget-title-color' => '#333333',
  'header-menu-active_item-font-color' => '#333333',
  'header-menu-active_item-font-color-style' => 'accent',
  'header-menu-active_item-font-gradient' => '90deg|#ffffff 30%|#000000 100%',
  'header-menu-decoration-other-active-color' => 'rgba(255,255,255,0.15)',
  'header-menu-decoration-other-active-color-style' => 'accent',
  'header-menu-decoration-other-active-gradient' => '135deg|rgba(255,255,255,0.15) 30%|rgba(0,0,0,0.15) 100%',
  'header-menu-decoration-other-active-line' => '0',
  'header-menu-decoration-other-active-line-color' => 'rgba(130,36,227,0.3)',
  'header-menu-decoration-other-active-line-color-style' => 'color',
  'header-menu-decoration-other-active-line-gradient' => '135deg|rgba(221,51,51,0.3) 30%|rgba(129,215,66,0.3) 100%',
  'header-menu-decoration-other-active-line-opacity' => 30,
  'header-menu-decoration-other-active-opacity' => 15,
  'header-menu-decoration-other-active-style' => 'background',
  'header-menu-decoration-other-border-radius' => 3,
  'header-menu-decoration-other-click_decor' => '1',
  'header-menu-decoration-other-click_decor-color' => 'rgba(255,255,255,0.2)',
  'header-menu-decoration-other-click_decor-color-style' => 'accent',
  'header-menu-decoration-other-click_decor-gradient' => '135deg|rgba(255,255,255,0.2) 30%|rgba(0,0,0,0.2) 100%',
  'header-menu-decoration-other-click_decor-opacity' => 20,
  'header-menu-decoration-other-hover-color' => 'rgba(255,255,255,0.15)',
  'header-menu-decoration-other-hover-color-style' => 'accent',
  'header-menu-decoration-other-hover-gradient' => '135deg|rgba(255,255,255,0.15) 30%|rgba(0,0,0,0.15) 100%',
  'header-menu-decoration-other-hover-line' => '0',
  'header-menu-decoration-other-hover-line-color' => 'rgba(221,51,51,0.23)',
  'header-menu-decoration-other-hover-line-color-style' => 'gradient',
  'header-menu-decoration-other-hover-line-gradient' => '135deg|rgba(255,255,255,0.23) 30%|rgba(0,0,0,0.23) 100%',
  'header-menu-decoration-other-hover-line-opacity' => 23,
  'header-menu-decoration-other-hover-style' => 'background',
  'header-menu-decoration-other-line_size' => '2',
  'header-menu-decoration-other-links-is_justified' => '1',
  'header-menu-decoration-other-opacity' => 15,
  'header-menu-decoration-style' => 'underline',
  'header-menu-decoration-underline-color' => '#1e73be',
  'header-menu-decoration-underline-color-style' => 'accent',
  'header-menu-decoration-underline-direction' => 'upwards',
  'header-menu-decoration-underline-gradient' => '135deg|#ffffff 30%|#000000 100%',
  'header-menu-decoration-underline-line_size' => '2',
  'header-menu-dividers-color' => 'rgba(17,17,17,0.14)',
  'header-menu-dividers-height' => 24,
  'header-menu-dividers-height-style' => 'custom',
  'header-menu-dividers-surround' => '0',
  'header-menu-font-color' => '#333333',
  'header-menu-font-is_capitalized' => false,
  'header-menu-hover-font-color' => '#333333',
  'header-menu-hover-font-color-style' => 'accent',
  'header-menu-hover-font-gradient' => '90deg|#8224e3 30%|#751257 100%',
  'header-menu-icon-size' => 14,
  'header-menu-item-margin' => '18px 14px 18px 14px',
  'header-menu-item-padding' => '4px 4px 4px 4px',
  'header-menu-item-surround_margins-custom-margin' => 30,
  'header-menu-item-surround_margins-style' => 'disabled',
  'header-menu-show_dividers' => '0',
  'header-menu-show_next_lvl_icons' => false,
  'header-menu-submenu-active-bg-color' => 'rgba(137,92,184,0.07)',
  'header-menu-submenu-active-bg-color-style' => 'accent',
  'header-menu-submenu-active-bg-gradient' => '90deg|#81d742 30%|#eeee22 100%',
  'header-menu-submenu-active-bg-opacity' => 7,
  'header-menu-submenu-active-font-color' => '#ffffff',
  'header-menu-submenu-active-font-color-style' => 'accent',
  'header-menu-submenu-active-font-gradient' => '90deg|#ffffff 30%|#000000 100%',
  'header-menu-submenu-bg-color' => 'rgba(255,255,255,1)',
  'header-menu-submenu-bg-hover' => 'background',
  'header-menu-submenu-bg-width' => 280,
  'header-menu-submenu-font-color' => '#333333',
  'header-menu-submenu-font-is_uppercase' => false,
  'header-menu-submenu-hover-bg-color' => 'rgba(137,92,184,0.07)',
  'header-menu-submenu-hover-bg-color-style' => 'accent',
  'header-menu-submenu-hover-bg-gradient' => '90deg|#81d742 30%|#eeee22 100%',
  'header-menu-submenu-hover-bg-opacity' => 7,
  'header-menu-submenu-hover-font-color' => '#895cb8',
  'header-menu-submenu-hover-font-color-style' => 'accent',
  'header-menu-submenu-hover-font-gradient' => '90deg|#81d742 30%|#eeee22 100%',
  'header-menu-submenu-icon-size' => 14,
  'header-menu-submenu-item-margin' => '0px 0px 0px 0px',
  'header-menu-submenu-item-padding' => '10px 10px 10px 10px',
  'header-menu-submenu-show_next_lvl_icons' => '1',
  'header-menu-submenu-subtitle-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => 10,
  ),
  'header-menu-submenu-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => 13,
  ),
  'header-menu-subtitle-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => 11,
  ),
  'header-menu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 17,
  ),
  'header-menu_close_icon-margin' => '30px 30px 30px 30px',
  'header-menu_icon-bg-border-radius' => 500,
  'header-menu_icon-bg-color' => 'rgba(255,255,255,0.75)',
  'header-menu_icon-bg-size' => 54,
  'header-menu_icon-color' => '#000000',
  'header-menu_icon-elements' => 
  array (
    'below_menu' => 
    array (
      0 => 'social_icons',
      1 => 'cart',
      2 => 'search',
      3 => 'phone',
    ),
  ),
  'header-menu_icon-elements-below_menu-padding' => '30px 0px 0px 0px',
  'header-menu_icon-elements-near_menu-font_color' => '#333333',
  'header-menu_icon-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 14,
  ),
  'header-menu_icon-hover-bg-color' => 'rgba(255,255,255,0.75)',
  'header-menu_icon-hover-color' => '#000000',
  'header-menu_icon-icons_style' => 'bold',
  'header-menu_icon-margin' => '0px 0px 0px 0px',
  'header-menu_icon-show_elements' => '1',
  'header-menu_icon-size' => 'medium',
  'header-mixed-bg-color' => 'rgba(255,255,255,1)',
  'header-mixed-decoration' => 'shadow',
  'header-mixed-decoration-color' => 'rgba(221,153,51,1)',
  'header-mobile-first_switch-after' => 1070,
  'header-mobile-first_switch-height' => 60,
  'header-mobile-first_switch-layout' => 'right_left',
  'header-mobile-first_switch-logo' => 'mobile',
  'header-mobile-floating_navigation' => 'sticky',
  'header-mobile-header-bg-color' => 'rgba(255,255,255,1)',
  'header-mobile-menu-align' => 'right',
  'header-mobile-menu-bg-color' => 'rgba(255,255,255,1)',
  'header-mobile-menu-bg-width' => 300,
  'header-mobile-menu-font-color' => '#333333',
  'header-mobile-menu-font-hover-color' => '#3c3e45',
  'header-mobile-menu-font-hover-color-style' => 'accent',
  'header-mobile-menu-font-hover-gradient' => '90deg|#b78ce2 30%|#1e73be 100%',
  'header-mobile-menu-font-is_capitalized' => false,
  'header-mobile-menu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 16,
  ),
  'header-mobile-menu_icon-bg-border-radius' => 0,
  'header-mobile-menu_icon-bg-color' => 'rgba(255,255,255,1)',
  'header-mobile-menu_icon-bg-enable' => '0',
  'header-mobile-menu_icon-bg-size' => 28,
  'header-mobile-menu_icon-color' => '#333333',
  'header-mobile-menu_icon-size' => 'small',
  'header-mobile-microwidgets-font-color' => '#333333',
  'header-mobile-microwidgets-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 13,
  ),
  'header-mobile-overlay-bg-color' => 'rgba(0,0,0,0.5)',
  'header-mobile-second_switch-after' => 1070,
  'header-mobile-second_switch-height' => 60,
  'header-mobile-second_switch-layout' => 'right_left',
  'header-mobile-second_switch-logo' => 'mobile',
  'header-mobile-submenu-font-is_capitalized' => false,
  'header-mobile-submenu-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => 13,
  ),
  'header-overlay-content-padding' => '40px 40px 40px 40px',
  'header-overlay-content-position' => 'center',
  'header-overlay-content-width' => '300px',
  'header-overlay-elements' => 
  array (
  ),
  'header-overlay-elements-below_menu-padding' => '0px 0px 0px 0px',
  'header-overlay-elements-top_line-padding' => '0px 0px 0px 0px',
  'header-overlay-icons_style' => 'light',
  'header-overlay-layout' => 'menu_icon',
  'header-overlay-layout-menu_icon-show_floating_logo' => '1',
  'header-overlay-layout-side_line-width' => 60,
  'header-overlay-layout-top_line-height' => 130,
  'header-overlay-layout-top_line-is_fullwidth' => '0',
  'header-overlay-layout-top_line-logo-position' => 'left',
  'header-overlay-logo-position' => 'inside',
  'header-overlay-menu-items_alignment' => 'center',
  'header-overlay-menu-items_link' => 'textwidth',
  'header-overlay-menu-padding' => '0px 0px',
  'header-overlay-menu-position' => 'v_top',
  'header-overlay-show_elements' => '0',
  'header-show_floating_navigation' => '1',
  'header-side-content-padding' => '40px 40px 40px 40px',
  'header-side-content-position' => 'left',
  'header-side-content-width' => '220px',
  'header-side-elements' => 
  array (
    'below_menu' => 
    array (
      0 => 'cart',
      1 => 'search',
      2 => 'phone',
      3 => 'social_icons',
    ),
  ),
  'header-side-elements-below_menu-padding' => '40px 0px 0px 0px',
  'header-side-elements-near_menu-font_color' => '#333333',
  'header-side-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => 13,
  ),
  'header-side-icons_style' => 'bold',
  'header-side-logo-position' => 'inside',
  'header-side-menu-items_alignment' => 'left',
  'header-side-menu-items_link' => 'textwidth',
  'header-side-menu-padding' => '0px 0px',
  'header-side-menu-position' => 'v_top',
  'header-side-menu-submenu-position' => 'down',
  'header-side-position' => 'left',
  'header-side-show_elements' => '1',
  'header-side-width' => '300px',
  'header-side_line-elements' => 
  array (
    'below_menu' => 
    array (
      0 => 'social_icons',
      1 => 'cart',
      2 => 'search',
      3 => 'phone',
    ),
  ),
  'header-side_line-elements-below_menu-padding' => '50px 0px 0px 0px',
  'header-side_line-elements-near_menu-font_color' => '#333333',
  'header-side_line-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto Condensed:700',
    'font_size' => 15,
  ),
  'header-side_line-icons_style' => 'bold',
  'header-side_line-show_elements' => '1',
  'header-side_line-width' => 60,
  'header-slide_out-content-padding' => '40px 40px 40px 40px',
  'header-slide_out-content-position' => 'left',
  'header-slide_out-content-width' => '220px',
  'header-slide_out-elements' => 
  array (
  ),
  'header-slide_out-elements-below_menu-padding' => '0px 0px 0px 0px',
  'header-slide_out-elements-top_line-padding' => '0px 0px 0px 0px',
  'header-slide_out-icons_style' => 'light',
  'header-slide_out-layout' => 'menu_icon',
  'header-slide_out-layout-menu_icon-show_floating_logo' => '1',
  'header-slide_out-layout-side_line-position' => 'above',
  'header-slide_out-layout-side_line-width' => 60,
  'header-slide_out-layout-top_line-height' => 130,
  'header-slide_out-layout-top_line-is_fullwidth' => '0',
  'header-slide_out-layout-top_line-logo-position' => 'left',
  'header-slide_out-logo-position' => 'inside',
  'header-slide_out-menu-items_alignment' => 'left',
  'header-slide_out-menu-items_link' => 'textwidth',
  'header-slide_out-menu-padding' => '0px 0px',
  'header-slide_out-menu-position' => 'v_top',
  'header-slide_out-overlay-animation' => 'slide',
  'header-slide_out-overlay-bg-color' => 'rgba(17,17,17,0.4)',
  'header-slide_out-overlay-bg-color-style' => 'color',
  'header-slide_out-overlay-bg-gradient' => '135deg|rgba(205,183,226,0.4) 30%|rgba(130,20,130,0.4) 100%',
  'header-slide_out-overlay-bg-opacity' => 40,
  'header-slide_out-overlay-blur' => '0',
  'header-slide_out-overlay-x_cursor' => '0',
  'header-slide_out-overlay-x_cursor-color' => '#000000',
  'header-slide_out-position' => 'right',
  'header-slide_out-show_elements' => '0',
  'header-slide_out-width' => '300px',
  'header-split-elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'phone',
      1 => 'address',
    ),
    'top_bar_right' => 
    array (
      0 => 'social_icons',
    ),
    'near_menu_left' => 
    array (
      0 => 'search',
    ),
    'near_menu_right' => 
    array (
      0 => 'cart',
    ),
  ),
  'header-split-elements-near_menu-font_color' => '#333333',
  'header-split-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto:700',
    'font_size' => 13,
  ),
  'header-split-elements-near_menu_left-padding' => '0px 20px 0px 20px',
  'header-split-elements-near_menu_right-padding' => '0px 20px 0px 20px',
  'header-split-height' => 100,
  'header-split-icons_style' => 'bold',
  'header-split-is_fullwidth' => '0',
  'header-split-menu-position' => 'fully_inside',
  'header-split-show_elements' => '1',
  'header-style-floating-choose_logo' => 'custom',
  'header-style-floating-logo-padding' => '0px 18px 0px 0px',
  'header-style-floating-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/wizard01.header-style-floating-logo-hd.png?w=84&h=84',
    1 => 0,
  ),
  'header-style-floating-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/wizard01.header-style-floating-logo-regular.png?w=42&h=42',
    1 => 0,
  ),
  'header-style-mixed-logo-padding' => '0px 0px 0px 0px',
  'header-style-mixed-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/wizard05.header-style-mixed-logo-hd.png?w=84&h=84',
    1 => 0,
  ),
  'header-style-mixed-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/wizard05.header-style-mixed-logo-regular.png?w=42&h=42',
    1 => 0,
  ),
  'header-style-mobile-logo-padding' => '0px 0px 0px 0px',
  'header-style-mobile-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/wizard01.header-style-mobile-logo-hd.png?w=84&h=84',
    1 => 0,
  ),
  'header-style-mobile-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/wizard01.header-style-mobile-logo-regular.png?w=42&h=42',
    1 => 0,
  ),
  'header-style-transparent-choose_logo' => 'custom',
  'header-style-transparent-logo-padding' => '0px 5px 0px 0px',
  'header-style-transparent-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin11r.header-style-transparent-logo-hd.png?w=114&h=114',
    1 => 0,
  ),
  'header-style-transparent-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin11r.header-style-transparent-logo-regular.png?w=57&h=57',
    1 => 0,
  ),
  'header-style-transparent-mobile-logo-padding' => '0px 0px 0px 0px',
  'header-style-transparent-mobile-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin11r.header-style-transparent-mobile-logo-hd.png?w=88&h=88',
    1 => 0,
  ),
  'header-style-transparent-mobile-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin11r.header-style-transparent-mobile-logo-regular.png?w=44&h=44',
    1 => 0,
  ),
  'header-top_line-elements' => 
  array (
    'top_line_right' => 
    array (
      0 => 'cart',
      1 => 'search',
      2 => 'phone',
      3 => 'social_icons',
    ),
  ),
  'header-top_line-elements-below_menu-padding' => '35px 0px 0px 0px',
  'header-top_line-elements-in_top_line-font_color' => '#333333',
  'header-top_line-elements-in_top_line-font_family' => 'Roboto',
  'header-top_line-elements-in_top_line-font_size' => 13,
  'header-top_line-elements-near_menu-font_color' => '#333333',
  'header-top_line-elements-near_menu-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => 13,
  ),
  'header-top_line-elements-top_line-padding' => '0px 0px 0px 0px',
  'header-top_line-elements-top_line_right-padding' => '0px 0px 0px 0px',
  'header-top_line-icons_style' => 'bold',
  'header-top_line-show_elements' => '1',
  'header-transparent-mobile-first_switch-logo' => 'mobile',
  'header-transparent-mobile-second_switch-logo' => 'mobile',
  'header-transparent_bg_color' => 'rgba(238,238,34,1)',
  'header_navigation' => 'slide_out',
  'image_hover-album_miniatures_style' => 'style_2',
  'image_hover-color' => 'rgba(12,162,224,0.2)',
  'image_hover-color_gradient' => '135deg|rgba(46,221,237,0.2) 30%|rgba(0,132,187,0.2) 100%',
  'image_hover-color_mode' => 'accent',
  'image_hover-default_icon' => 'none',
  'image_hover-onclick_animation' => false,
  'image_hover-opacity' => 20,
  'image_hover-project_icons_style' => 'outline',
  'image_hover-project_rollover_color' => 'rgba(0,0,0,0.85)',
  'image_hover-project_rollover_color_gradient' => '135deg|rgba(46,221,237,0.85) 30%|rgba(0,132,187,0.85) 100%',
  'image_hover-project_rollover_color_mode' => 'accent',
  'image_hover-project_rollover_opacity' => 85,
  'image_hover-style' => 'none',
  'input_bg_color' => 'rgba(253,253,253,1)',
  'input_border_color' => 'rgba(51,51,51,0.12)',
  'input_border_radius' => 1,
  'input_border_width' => 1,
  'input_color' => '#8b8d94',
  'input_height' => 38,
  'layout-menu_icon-position' => 'menu_icon_right',
  'layout-menu_icon-show_floating_logo' => '1',
  'layout-side_line-position' => 'above',
  'layout-side_line-v_position' => 'left',
  'layout-top_line-height' => 80,
  'layout-top_line-is_fullwidth' => '0',
  'layout-top_line-is_sticky' => '1',
  'layout-top_line-logo-position' => 'center',
  'message_bg_color' => '',
  'message_color' => '#ffffff',
  'page_title-background-style-transparent-color_scheme' => 'light',
  'page_title-padding' => '25px 20px',
  'post-show_fancy_categories' => '1',
  'post-show_fancy_date' => '1',
  'preset' => 'wizard01',
  'sidebar-bg_color' => 'rgba(247,247,248,1)',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-decoration' => 'none',
  'sidebar-decoration_outline_color' => 'rgba(0,0,0,0.06)',
  'sidebar-distance_to_content' => 50,
  'sidebar-divider-horizontal' => '0',
  'sidebar-divider-vertical' => '1',
  'sidebar-headers_color' => '#333333',
  'sidebar-primary_text_color' => '#85868c',
  'sidebar-responsiveness' => 990,
  'sidebar-vertical_distance' => 60,
  'sidebar-visual_style' => 'with_dividers',
  'sidebar-width' => '350px',
  'social_buttons-product' => 
  array (
    0 => 'twitter',
    1 => 'pinterest',
    2 => 'linkedin',
    3 => 'whatsapp',
    4 => 'facebook',
  ),
  'social_buttons-product-button_title' => 'Share this product',
  'social_buttons-visibility' => 'allways',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_color' => '#f8f8f9',
  'stripes-stripe_1_content_boxes_bg_color' => '#ffffff',
  'stripes-stripe_1_content_boxes_bg_opacity' => 100,
  'stripes-stripe_1_content_boxes_decoration' => 'none',
  'stripes-stripe_1_content_boxes_decoration_outline_color' => '#dd3333',
  'stripes-stripe_1_content_boxes_decoration_outline_opacity' => 100,
  'stripes-stripe_1_headers_color' => '#3b3f4a',
  'stripes-stripe_1_outline' => 'hide',
  'stripes-stripe_1_outline_color' => '#44bb70',
  'stripes-stripe_1_outline_opacity' => 100,
  'stripes-stripe_1_text_color' => '#787d85',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_color' => '#23262d',
  'stripes-stripe_2_content_boxes_bg_color' => '#ffffff',
  'stripes-stripe_2_content_boxes_bg_opacity' => 10,
  'stripes-stripe_2_content_boxes_decoration' => 'none',
  'stripes-stripe_2_content_boxes_decoration_outline_color' => '#ffffff',
  'stripes-stripe_2_content_boxes_decoration_outline_opacity' => 15,
  'stripes-stripe_2_headers_color' => '#ffffff',
  'stripes-stripe_2_outline' => 'hide',
  'stripes-stripe_2_outline_color' => '#ffffff',
  'stripes-stripe_2_outline_opacity' => 15,
  'stripes-stripe_2_text_color' => '#8b9199',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin22.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_color' => '#000000',
  'stripes-stripe_3_content_boxes_bg_color' => '#ffffff',
  'stripes-stripe_3_content_boxes_bg_opacity' => 10,
  'stripes-stripe_3_content_boxes_decoration' => 'none',
  'stripes-stripe_3_content_boxes_decoration_outline_color' => '#ffffff',
  'stripes-stripe_3_content_boxes_decoration_outline_opacity' => 19,
  'stripes-stripe_3_headers_color' => '#ffffff',
  'stripes-stripe_3_outline' => 'hide',
  'stripes-stripe_3_outline_color' => '#252728',
  'stripes-stripe_3_outline_opacity' => 100,
  'stripes-stripe_3_text_color' => '#ffffff',
  'top-bar-height' => 36,
  'top_bar-bg-color' => '#1a1c20',
  'top_bar-bg-image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-bg-style' => 'disabled',
  'top_bar-font-color' => '#ffffff',
  'top_bar-font-is_capitalized' => false,
  'top_bar-line-color' => 'rgba(255,255,255,0.12)',
  'top_bar-line-in-transparent-header' => false,
  'top_bar-line_size' => '1',
  'top_bar-line_style' => 'solid',
  'top_bar-padding' => '5px 5px 0px',
  'top_bar-typography' => 
  array (
    'font_family' => 'Roboto',
    'font_size' => 13,
  ),
  'woocommerce-product_zoom' => '1',
  'woocommerce_cart_padding' => '60px 0px',
  'woocommerce_cart_switch' => 990,
  'woocommerce_product_img_width' => '50%',
  'woocommerce_product_switch' => 778,
  'woocommerce_rel_products_max' => 6,
  'woocommerce_steps-bg_opacity' => 100,
  'woocommerce_steps_bg_color' => '#ffffff',
  'woocommerce_steps_color' => '#333333',
);